\version "2.19.80"

\header {
  title = \markup \fontsize #3 \bold "PRESSURE & CHROME"
    composer = "Jacquelyn Bell (aka JacKeys)"
      meter = "Fast & Heavy (q = 134-138)"
      }

      \paper {
        paper-height = 11\in
          paper-width = 8.5\in
            tagline = ##f
            }

            % --- CUSTOM STICKING SHORTCUTS ---
            R = _\markup \bold "R"
            L = _\markup \bold "L"

            % --- SNARE DRUM ---
            snareLine = \drummode {
              \clef percussion
                \time 4/4
                  
                    \mark \markup \bold "Section I: Intro Check"
                      sn4:16\R r8 sn16\L sn\R sn8->\L sn16\R sn\L sn4->\R |
                        sn4:16\R r8 sn16\L sn\R sn8->\L sn8->\R sn4->\L |
                          
                            \mark \markup \bold "Section II: Jersey Club Groove"
                              \repeat volta 2 {
                                  sn8->\R sn16\L sn\R sn8->\L sn16\R sn\L sn8->\R sn16\L sn\R sn8->\L sn16\R sn\L |
                                      sn8->\R sn16\L sn\R sn8\z\L sn\z\R sn16->\L sn\R sn8->\L sn4->\R |
                                        }
                                          
                                            \mark \markup \bold "Section III: Atlanta Pocket Roll Groove"
                                              \repeat volta 2 {
                                                  sn8->\R sn16:32\L sn:32\R sn8->\L sn16\R sn\L sn8->\R sn16:32\L sn:32\R sn8->\L sn16\R sn\L |
                                                      sn16->\R sn\L sn8->\R sn16:32\L sn:32\R sn8->\L sn8\z\R sn\z\L sn4->\R |
                                                        }
                                                          
                                                            \mark \markup \bold "Section IV: Feature Quint Solo (Snare Pattern)"
                                                              \repeat volta 2 {
                                                                  sn8->\R sn16\L sn\R sn8->\L sn4->\R sn8->\L sn16\R sn\L sn8->\R |
                                                                      sn8->\L sn16\R sn\L sn8->\R sn16\L sn\R sn4->\L r4 |
                                                                        }

                                                                          \mark \markup \bold "Section V: Feature Snare Solo"
                                                                            \repeat volta 2 {
                                                                                sn16->\R sn\L sn8\z\R sn16->\L sn\R sn8->\L sn16:32\R sn:32\L sn8->\R sn16\L sn\R sn8->\L |
                                                                                    sn16->\R sn\L sn8\z\R sn16->\L sn\R sn8->\L sn8\z\R sn\z\L sn4->\R |
                                                                                      }

                                                                                        \mark \markup \bold "Section VI: Call & Response Feature"
                                                                                          \repeat volta 2 {
                                                                                              sn8->\R sn16\L sn\R sn8->\L r8 r2 |
                                                                                                  sn8->\R sn16\L sn\R sn8->\L sn16\R sn\L sn8->\R sn16\L sn\R sn4->\L |
                                                                                                    }

                                                                                                      \mark \markup \bold "Section VII: The Engine (Full Line Build)"
                                                                                                        sn8\p\R sn16\L sn\R sn8\L sn16\R sn\L sn8\< \R sn16\L sn\R sn8\L sn16\R sn\! \L |
                                                                                                          sn8\R sn16\L sn\R sn8\L sn16\R sn\L sn8\ff\R sn8->\L sn4->\R |

                                                                                                            \mark \markup \bold "Section VIII: Outro"
                                                                                                              sn4:32\ff\R sn4:32\L sn4:32\R r4 \bar "|."
                                                                                                              }

                                                                                                              % --- SINGLE TENORS ---
                                                                                                              tenorLine = \drummode {
                                                                                                                \clef percussion
                                                                                                                  \time 4/4
                                                                                                                    
                                                                                                                      hh4-> r8 hh16 hh hh8-> r4 hh4-> |
                                                                                                                        hh4-> r8 hh16 hh hh8-> hh8-> hh4-> |
                                                                                                                          
                                                                                                                            \repeat volta 2 {
                                                                                                                                tomh8->\R tomh16\L tomh\R tomh8->\L tomh16\R tomh\L tomh8->\R tomh16\L tomh\R tomh8->\L tomh16\R tomh\L |
                                                                                                                                    tomh8->\R tomh16\L tomh\R hh8\L hh8\R tomh16->\L tomh\R tomh8->\L hh4->\R |
                                                                                                                                      }
                                                                                                                                        
                                                                                                                                          \repeat volta 2 {
                                                                                                                                              tomh8->\R tomh8\L hh8->\R tomh16\L tomh\R tomh8->\L tomh8\R hh8->\L tomh16\R tomh\L |
                                                                                                                                                  tomh16->\R tomh\L tomh8->\R hh8\L tomh16\R tomh\L tomh8->\R hh8\L hh4->\R |
                                                                                                                                                    }

                                                                                                                                                      \repeat volta 2 {
                                                                                                                                                          hh4->\R r4 hh4->\L r4 |
                                                                                                                                                              hh4->\R r4 hh4->\L r4 |
                                                                                                                                                                }

                                                                                                                                                                  \repeat volta 2 {
                                                                                                                                                                      hh8->\R tomh16\L tomh\R hh8->\L tomh8\R hh8->\L tomh16\R tomh\L hh8->\R tomh8\L |
                                                                                                                                                                          hh8->\R tomh16\L tomh\R hh8->\L tomh8\R hh4->\L r4 |
                                                                                                                                                                            }
                                                                                                                                                                              
                                                                                                                                                                                \repeat volta 2 {
                                                                                                                                                                                    r2 tomh8->\R tomh16\L tomh\R tomh4->\L |
                                                                                                                                                                                        tomh8\R tomh16\L tomh\R tomh8->\L tomh16\R tomh\L tomh8\R tomh16\L tomh\R hh4->\L |
                                                                                                                                                                                          }

                                                                                                                                                                                            tomh8\p\R tomh16\L tomh\R tomh8\L tomh16\R tomh\L tomh8\< \R tomh16\L tomh\R tomh8\L tomh16\R tomh\! \L |
                                                                                                                                                                                              tomh8\R tomh16\L tomh\R tomh8\L tomh16\R tomh\L tomh8\ff\R tomh8->\L hh4->\R |

                                                                                                                                                                                                hh4-> hh4-> hh4-> r4 \bar "|."
                                                                                                                                                                                                }

                                                                                                                                                                                                % --- QUINTS (5 DRUMS WITH SPOCK) ---
                                                                                                                                                                                                quintLine = \drummode {
                                                                                                                                                                                                  \clef percussion
                                                                                                                                                                                                    \time 4/4
                                                                                                                                                                                                      
                                                                                                                                                                                                        hihat4-> r8 hihat16 hihat hihat8-> r4 hihat4-> |
                                                                                                                                                                                                          hihat4-> r8 hihat16 hihat hihat8-> hh8-> hh4-> |
                                                                                                                                                                                                            
                                                                                                                                                                                                              \repeat volta 2 {
                                                                                                                                                                                                                  hihat8\R toml16\L tomml\R tomh8\L tommh16\R tomh\L tomml8\R toml16\L tomml\R tomh8\L tommh16\R tomh\L |
                                                                                                                                                                                                                      hihat8\R toml16\L tomml\R hihat8\R hh8\L tommh16->\R tomh\L tomml8->\R hh4->\L |
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                          
                                                                                                                                                                                                                            \repeat volta 2 {
                                                                                                                                                                                                                                hihat8\R toml16\L tomml\R tomh8\L tommh16\R tomh\L tomml8\R toml16\L tomml\R tomh8\L tommh16\R tomh\L |
                                                                                                                                                                                                                                    toml16\L tomml\R tomh8\L tommh16\R tomh\L tomml8\R hihat8\L hh4->\R r4 |
                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                        % Section IV: Feature Quint Solo
                                                                                                                                                                                                                                          \repeat volta 2 {
                                                                                                                                                                                                                                              hihat8->\R toml16\L tomml\R tomh8->\L tommh16\R tomh\L hihat8->\R tommh16\L tomh\R tomml8->\L toml8->\R |
                                                                                                                                                                                                                                                  hihat16->\L toml\R tomml8->\L tomh16\R tommh\L tomh8->\R tomml16\L toml\R hihat8->\L hh4->\R |
                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                      \repeat volta 2 {
                                                                                                                                                                                                                                                          hihat8\R toml16\L tomml\R hihat8\L tommh16\R tomh\L tomml8\R toml16\L tomml\R hihat8\L tommh8\R |
                                                                                                                                                                                                                                                              hihat8\R toml16\L tomml\R hihat8\L tommh8\R hh4->\L r4 |
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                    \repeat volta 2 {
                                                                                                                                                                                                                                                                        hihat8->\R toml8->\L tomml8->\R r8 r2 |
                                                                                                                                                                                                                                                                            hihat8\R toml16\L tomml\R tomh8\L tommh16\R tomh\L tomml8\R toml16\L tomml\R hh4->\R |
                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                toml8\p\R tomml16\L tomh\R tommh8\L toml16\R tomml\L tomh8\< \R tommh16\L toml\R tomml8\L tomh16\R tommh\! \L |
                                                                                                                                                                                                                                                                                  hihat8\R toml16\L tomml\R tomh8\L tommh16\R tomh\L hihat8\ff\R hh8->\L hh4->\R |

                                                                                                                                                                                                                                                                                    hh4-> hh4-> hh4-> r4 \bar "|."
                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                    % --- CYMBALS ---
                                                                                                                                                                                                                                                                                    cymbalLine = \drummode {
                                                                                                                                                                                                                                                                                      \clef percussion
                                                                                                                                                                                                                                                                                        \time 4/4
                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                            cymr4 r8 cymr16 cymr cymr8 r4 cymr4 |
                                                                                                                                                                                                                                                                                              cymr4 r8 cymr16 cymr cymr8 cymr cymr4-> |
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                  \repeat volta 2 {
                                                                                                                                                                                                                                                                                                      cymr8 cymr16 cymr cymr8 cymr16 cymr cymr8 cymr16 cymr cymr8 cymr16 cymr |
                                                                                                                                                                                                                                                                                                          cymr8 cymr16 cymr cymr8 cymr cymr4-> r2 |
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                \repeat volta 2 {
                                                                                                                                                                                                                                                                                                                    cymr8 cymr16 cymr cymr8 cymr16 cymr cymr8 cymr16 cymr cymr8 cymr16 cymr |
                                                                                                                                                                                                                                                                                                                        cymr16 cymr cymr8 cymr16 cymr cymr8 cymr4-> r4 |
                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                            \repeat volta 2 {
                                                                                                                                                                                                                                                                                                                                R1 |
                                                                                                                                                                                                                                                                                                                                    R1 |
                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                        \repeat volta 2 {
                                                                                                                                                                                                                                                                                                                                            cymr8 cymr16 cymr cymr8 cymr16 cymr cymr8 cymr16 cymr cymr8 cymr16 cymr |
                                                                                                                                                                                                                                                                                                                                                cymr8 cymr16 cymr cymr8 cymr cymr4-> r4 |
                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                      \repeat volta 2 {
                                                                                                                                                                                                                                                                                                                                                          r2 cymr8-> cymr8-> cymr4-> |
                                                                                                                                                                                                                                                                                                                                                              cymr8 cymr16 cymr cymr8 cymr16 cymr cymr4-> r4 |
                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                  cymr8\p cymr16 cymr cymr8 cymr16 cymr cymr8\< cymr16 cymr cymr8 cymr16 cymr\! |
                                                                                                                                                                                                                                                                                                                                                                    cymr8 cymr16 cymr cymr8 cymr16 cymr cymr8\ff cymr4-> r8 |

                                                                                                                                                                                                                                                                                                                                                                      cymr4-> cymr4-> cymr4-> r4 \bar "|."
                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                      % --- BASS DRUM (5-DRUM SPLIT) ---
                                                                                                                                                                                                                                                                                                                                                                      bassLine = \drummode {
                                                                                                                                                                                                                                                                                                                                                                        \clef percussion
                                                                                                                                                                                                                                                                                                                                                                          \time 4/4
                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                              bd1 4 r8 bd2 16 bd3 bd5 4 r4 |
                                                                                                                                                                                                                                                                                                                                                                                bd1 4 r8 bd2 16 bd3 bd5 8 bd4 bd3 4-> |
                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                    \repeat volta 2 {
                                                                                                                                                                                                                                                                                                                                                                                        bd1 8 bd2 16 bd3 bd4 8 bd5 16 bd4 bd3 8 bd2 16 bd1 bd2 8 bd3 8 |
                                                                                                                                                                                                                                                                                                                                                                                            bd4 16 bd5 bd4 8 bd3 8 bd2 16 bd1 bd2 8 bd1 4-> |
                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                  \repeat volta 2 {
                                                                                                                                                                                                                                                                                                                                                                                                      bd1 16 bd2 bd3 8 bd4 16 bd5 bd4 8 bd3 16 bd2 bd1 8 bd2 16 bd3 bd4 8 |
                                                                                                                                                                                                                                                                                                                                                                                                          bd5 16 bd4 bd3 8 bd2 16 bd1 bd2 8 bd5 4-> r4 |
                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                              \repeat volta 2 {
                                                                                                                                                                                                                                                                                                                                                                                                                  bd1 4\p bd3 8 bd2 16 bd1 bd5 4 bd3 8 bd4 16 bd5 |
                                                                                                                                                                                                                                                                                                                                                                                                                      bd1 4 bd3 8 bd2 16 bd1 bd5 4-> r4 |
                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                          \repeat volta 2 {
                                                                                                                                                                                                                                                                                                                                                                                                                              bd1 16 bd2 bd3 8 bd4 16 bd5 bd4 8 bd3 16 bd2 bd1 8 bd2 16 bd3 bd4 8 |
                                                                                                                                                                                                                                                                                                                                                                                                                                  bd5 16 bd4 bd3 8 bd2 16 bd1 bd5 4-> r4 |
                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                        \repeat volta 2 {
                                                                                                                                                                                                                                                                                                                                                                                                                                            bd1 8 bd2 8 bd3 8 r8 r2 |
                                                                                                                                                                                                                                                                                                                                                                                                                                                bd1 8 bd2 16 bd3 bd4 8 bd5 16 bd4 bd3 8 bd1 4-> |
                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                    bd1 8\p bd2 16 bd3 bd4 8 bd5 16 bd4 bd3 8\< bd2 16 bd1 bd2 8 bd3\! 8 |
                                                                                                                                                                                                                                                                                                                                                                                                                                                      bd4 16 bd5 bd4 8 bd3 16 bd2 bd5 4->\ff bd1 4-> |

                                                                                                                                                                                                                                                                                                                                                                                                                                                        bd1 4\ff bd3 4 bd5 4 r4 \bar "|."
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                        \score {
                                                                                                                                                                                                                                                                                                                                                                                                                                                          \new StaffGroup <<
                                                                                                                                                                                                                                                                                                                                                                                                                                                              \new DrumStaff \with {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    instrumentName = #"Snare"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          shortInstrumentName = #"S.D."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                drumStyleTable = #percussion-style
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } \snareLine

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        \new DrumStaff \with {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              instrumentName = #"Single Tenors"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    shortInstrumentName = #"T.D."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          drumStyleTable = #percussion-style
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              } \tenorLine

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  \new DrumStaff \with {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        instrumentName = #"Quints"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              shortInstrumentName = #"Q.T."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    drumStyleTable = #percussion-style
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } \quintLine

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            \new DrumStaff \with {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  instrumentName = #"Cymbals"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        shortInstrumentName = #"Cym."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              drumStyleTable = #percussion-style
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } \cymbalLine

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      \new DrumStaff \with {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            instrumentName = #"Bass Line"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  shortInstrumentName = #"B.D."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        drumStyleTable = #percussion-style
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } \bassLine
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  \layout {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      \context {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            \Score
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  proportionalNotationDuration = #(ly:make-moment 1/16)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \midi {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \tempo 4 = 136
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                